### PR TITLE
Fix testing on CI

### PR DESCRIPTION
**Pull request by uilianries**
- Update README using badges
- Fix unit tests on CI

### CODE REVIEW

**Comment by uilianries** [comment]
@SSE4 pylint is reporting about some errors, any idea?

E0601:Using variable 'travis_account' before assignment
E0601:Using variable 'appveyor_account' before assignment
E0601:Using variable 'github_account' before assignment
W0612:Unused variable 'travis_headers'
W0612:Unused variable 'appveyor_headers'

**Comment by SSE4** [comment]
I'll take a look into pylint errors

**Review by SSE4 — APPROVED** [review]
LGTM

**Comment by SSE4** [comment]
@uilianries I've fixed issues with global variables
unfortunately travis still fails with obscure error:
```
invalid option "--password="
```

**Comment by uilianries** [comment]
@SSE4 I think this error is related to pypi password. I'll check later, thanks

**Comment by uilianries** [comment]
Done!

https://travis-ci.org/bincrafters/bincrafters-envy/jobs/433952752

Also I released the tag 0.1.1: https://github.com/bincrafters/bincrafters-envy/releases/tag/0.1.1

And the CI just upload our package: https://pypi.org/project/bincrafters-envy/

**Pull request merged**
